feat: Add minify_js to decrease file sizes
koesterlab/datavzrd pull request #210
Opened 2022-09-30 14:02 UTC by tedil

This PR uses `minify_js` to minify rendered js files before writing. This should reduce file sizes slightly.
I probably haven't caught all places js files are written, feel free to add any that I missed ;)

(It may also be interesting to minify the html files, haven't looked into that, yet)

2022-09-30 14:24 UTC, fxwiegand requested changes
I think there are also some plot.js files that could be minified. I'll add that quickly.

2022-09-30 14:24 UTC, fxwiegand commented on src/render/portable/utils.rs
> +        out.write_all(&minified)?;
I think all files written here are already minified except the one css file that is not big at all and already included in each report one time.

```suggestion
        out.write_all(file.as_bytes())?;
```

2022-09-30 14:31 UTC, fxwiegand approved these changes

2022-10-11 08:31 UTC, johanneskoester approved these changes

2022-10-11 08:31 UTC, merged