feat: Add basic excel export option
koesterlab/datavzrd pull request #258
Opened 2022-11-09 09:40 UTC by fxwiegand

This PR adds a basic excel export option and therefore close #257. This could be extended in the future by also using the config file and rendering heatmaps etc. into the excel worksheet.

2022-11-10 15:48 UTC, johanneskoester commented
The plots should not be rendered into the excel sheet. Only the tabular views.

2022-11-10 15:48 UTC, johanneskoester requested changes
The plots should not be rendered into the excel sheet. Only the tabular views.

2022-11-10 15:52 UTC, fxwiegand commented
> The plots should not be rendered into the excel sheet. Only the tabular views.

Makes sense! Just updated it!

2022-11-11 12:28 UTC, johanneskoester approved these changes

2022-11-11 12:28 UTC, merged